local M = {}
M.map = {
	[[AAAAAAAAAAAAAAAAAAAAAA]],
	[[AAAAAAAABBBBBAAAAAAAAA]],
	[[AAABBAABCDECDBAAABBAAA]],
	[[AABCFBBGAHICICBABAJBAA]],
	[[ABDFBBGAACJJIBBBAKBKBA]],
	[[ABDBABIHKKKBBABLKBBKBA]],
	[[AABAABKKKKIABKKKKBBMBA]],
	[[AAAAABMNMMIKIIKLOPQMBA]],
	[[AAAAABLMMRPMPKLBBJKBAA]],
	[[AAAAAABSKMIPISBAABBAAA]],
	[[AAAAAAABRSSTTBAAAAAAAA]],
	[[AAAAAAAABBBBBAAAAAAAAA]],
	[[AAAAAAAABSSSBAAAAAAAAA]],
	[[AAAAABBBBUTBAAAAAAAAAA]],
	[[AAAABSVSBMMBBBBAAAAAAA]],
	[[AAAABBBBBMKBSWWBAAAAAA]],
	[[AAABMPVVBKUVUPMKBAAAAA]],
	[[AABPPPUUWVXPIMMMPBAAAA]],
	[[AABYBMMPSLPMPPBBPBAAAA]],
	[[AAABABKUMBMKUBAABAAAAA]],
	[[AAAAAABBMPMPBAAAAAAAAA]],
	[[AAAAAAAABBBBAAAAAAAAAA]],
	[[AAAAAAAAAAAAAAAAAAAAAA]],
}

M.colors = {
	["A"] = { fg = "#ffffff" },
	["B"] = { fg = "#2b2b2b" },
	["C"] = { fg = "#2dcf34" },
	["D"] = { fg = "#0d220b" },
	["E"] = { fg = "#232f22" },
	["F"] = { fg = "#008900" },
	["G"] = { fg = "#013200" },
	["H"] = { fg = "#fff6ff" },
	["I"] = { fg = "#005400" },
	["J"] = { fg = "#39c838" },
	["K"] = { fg = "#33cc34" },
	["L"] = { fg = "#008206" },
	["M"] = { fg = "#30cf2e" },
	["N"] = { fg = "#4c9c4a" },
	["O"] = { fg = "#005c00" },
	["P"] = { fg = "#30cc3b" },
	["Q"] = { fg = "#060808" },
	["R"] = { fg = "#4a8b4a" },
	["S"] = { fg = "#008300" },
	["T"] = { fg = "#004300" },
	["U"] = { fg = "#004d00" },
	["V"] = { fg = "#002900" },
	["W"] = { fg = "#077f00" },
	["X"] = { fg = "#002100" },
	["Y"] = { fg = "#58b454" },
}
return M
